version: '3'

dotenv: ['.env']

tasks:

  default:
    cmds:
      - task --list-all

  contracts-build:
    dir: contracts
    cmds:
      - forge fmt
      - forge build --out "../dapp/abi"

  contracts-test:
    dir: contracts
    cmds:
      - forge test -vvv --gas-report

  contracts-deploy-script:
    dir: contracts/script
    cmds:
      - forge script --rpc-url {{.RPC_URL}}
                     --account defaultKey
                     --sender {{.PUBLIC_KEY_LOCAL}}
                     --broadcast
                     --password-file "../.password"
                     DeployZombieOwnership

  contracts-deploy:
    dir: contracts
    cmds:
      - forge create --rpc-url {{.RPC_URL}}
                     --account defaultKey
                     --password-file ".password"
                     src/cryptozombies/zombieownership.sol:ZombieOwnership
                     # --interactive
                     # --private-key {{.PRIVATE_KEY_LOCAL}}
  frontend-build:
    dir: dapp
    cmds:
      - pnpm i
      - pnpm run build

  frontend-run:
    dir: dapp
    deps: [frontend-build]
    cmds:
      - pnpm run dev --open
