version: '3'

env:
  ENV: local

dotenv: ['.env', '.env.{{.ENV}}']

tasks:

  default:
    cmds:
      - task --list-all

  contracts-build:
    dir: contracts
    cmds:
      - forge fmt
      - forge build --out "../dapp/abi"

  contracts-test:
    dir: contracts
    cmds:
      - forge test -vvv --gas-report

  contracts-gas:
    dir: contracts
    cmds:
      - forge snapshot

  contracts-deploy-script:
    dir: contracts/script
    cmds:
      - forge script --rpc-url {{.RPC_URL}}
                     --account defaultKey
                     --sender {{.PUBLIC_KEY}}
                     --broadcast
                     --password-file "../.password"
                     DeployZombieOwnership
      - forge script --rpc-url {{.RPC_URL}}
                     --account defaultKey
                     --sender {{.PUBLIC_KEY}}
                     --broadcast
                     --password-file "../.password"
                     DeployFundMe

  contracts-deploy:
    dir: contracts
    cmds:
      - forge create --rpc-url {{.RPC_URL}}
                     --account defaultKey
                     --password-file ".password"
                     src/cryptozombies/zombieownership.sol:ZombieOwnership

  fundme-FundFundMe:
    dir: contracts/script
    cmds:
      - forge script --rpc-url {{.RPC_URL}}
                     --account defaultKey
                     --sender {{.PUBLIC_KEY}}
                     --broadcast
                     --password-file "../.password"
                     InteractionsFundMe.s.sol:FundFundMe

  fundme-WithdrawFundMe:
    dir: contracts/script
    cmds:
      - forge script --rpc-url {{.RPC_URL}}
                     --account defaultKey
                     --sender {{.PUBLIC_KEY}}
                     --broadcast
                     --password-file "../.password"
                     InteractionsFundMe.s.sol:WithdrawFundMe

  frontend-build:
    dir: dapp
    cmds:
      - pnpm i
      - pnpm run build

  frontend-run:
    dir: dapp
    deps: [frontend-build]
    cmds:
      - pnpm run dev --open
