version: '3'

dotenv: ['.env']

tasks:

  default:
    cmds:
      - task --list-all

  contracts-build:
    dir: contracts
    cmds:
      - forge build

  contracts-test:
    dir: contracts
    cmds:
      - forge test --gas-report

  contracts-deploy:
    dir: contracts
    cmds:
      - forge create --rpc-url src/zombiefeeding.sol:ZombieFeeding