version: '3'

dotenv: ['.env']

tasks:

  default:
    cmds:
      - task --list-all

  contracts-build:
    dir: contracts
    cmds:
      - forge fmt
      - forge build

  contracts-test:
    dir: contracts
    cmds:
      - forge test --gas-report

  contracts-deploy:
    dir: contracts
    cmds:
      - forge create --rpc-url "http://127.0.0.1:8545"
                     --private-key "{{.PRIVATE_KEY_LOCAL}}"
                     src/zombiefeeding.sol:ZombieFeeding