name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  FOUNDRY_PROFILE: ci

jobs:

  foundry:
    name: Cryptozombies Foundry project
    defaults:
      run:
        working-directory: contracts
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

  dapp:
    name: Vue.js dapp
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dapp
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - name: Installing project dependencies
      run: pnpm install
    - name: Build and tests
      run: |
        pnpm run build
        pnpm run coverage 

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
